---
customers:
  - label: Meijer
    handle: mj
    widgets:
      - label: Tags
        handle: tags
        stages:
          - downloading
          - processing_tag_data
          - generating_print_files
          - finished
      - label: PEG Tags
        handle: peg_tags
        stages:
          - mapping_data
          - updating_pog_trigger
          - extracting_data
          - sdm_processing
          - generating_mj2.5x1_print_files
          - generating_mj2x1_print_files
          - generating_stats
          - finished
      - label: Healthy Living
        handle: healthy_living
        stages:
          - requesting_upcs_removed
          - mapping_upcs_removed
          - requesting_gas_station
          - requesting_stores
          - mapping_data
          - removing_unchanged_data
          - extracting_data
          - sdm_processing
          - generating_mj2.5x1_print_files
          - generating_stats
          - finished
      - label: Strips
        handle: strips
        stages:
          - staging
          - preparing_print_files
          - generating_5ft_files
          - generating_4ft_files
          - finished
      - label: Strip Data Pull
        handle: strip_data_pull
        stages:
          - checking_psas
          - requesting_psas
          - requesting_data
          - resubmit
          - missing_ilcs
          - pricing_report
          - cleanup
          - finished
      - label: Sign Kit
        handle: signkit
        stages:
          - prep
          - executing_predownload_features
          - mapping_data
          - executing_postdownload_features
          - extracting_data
          - extracting_nexgen_data
          - sdm_processing
          - generating_mdb2x3_print_files
          - generating_mf5x3_print_files
          - generating_mj5x7_print_files
          - generating_mj5x7pr_print_files
          - generating_mj8x2pr_print_files
          - generating_mj7x11pr_print_files
          - generating_mj8x4_print_files
          - generating_mj6x4_print_files
          - generating_mjza2x2_print_files
          - generating_vinyl_print_files
          - generating_mj7x11_print_files
          - generating_mj2x2_print_files
          - generating_mj2x3_print_files
          - generating_stats
          - finished
  - label: SpartanNash
    handle: sn
    widgets:
      - label: Weekly Processing
        handle: weekly_processing
        stages:
          - downloading
          - sdm
          - batching
          - pulling_pdfs_to_generate
          - extracting_pdf_data
          - preparing_pdfs
          - creating_pdfs
          - building_stats
          - finished
      - label: Planogram Signs
        handle: planogram
        stages:
          - loading_store_data
          - processing_updates
          - creating_sign_files
          - sending_to_sdm
          - finished
      - label: Service Case Signs
        handle: service_case
        stages:
          - finding_files
          - processing_weekly_signs
          - finding_additional_files
          - processing_additional_signs
          - finished
      - label: Digital Coupons
        handle: digital_coupon
        stages:
          - matching_files
          - loading_coupon_data
          - processing_coupons
          - sending_to_sdm
          - finished
      - label: Sign Kit
        handle: signkit
        stages:
          - loading_sign_data
          - creating_sign_files
          - sending_to_sdm
          - finished
      - label: Import Files
        handle: import_files
        stages:
          - master_product_data
          - label_request
          - price_change_data
          - price_item_data
          - finished
      - label: Graphic Services
        handle: graphic_services
        stages:
          - staging_files
          - cleaning_renders
          - routing_files
          - sorting_files
          - writing_fusion_pro_inputs
          - creating_pdfs
          - generating_stats
          - moving_production_files
          - finished
  - label: Houchens
    handle: ho
    widgets:
      - label: Weekly
        handle: weekly
        stages:
          - downloading
          - processing_tag_data
          - generating_print_files
          - finished
      - label: Digital Coupons
        handle: digital_coupons
        stages:
          - downloading
          - processing_tag_data
          - generating_print_files
          - finished
      - label: Hold for Crossmark
        handle: crossmark
        stages:
          - downloading
          - processing_tag_data
          - generating_print_files
          - finished
      - label: Case Ready
        handle: case
        stages:
          - downloading
          - processing_tag_data
          - generating_print_files
          - finished
      - label: Table Tags
        handle: table
        stages:
          - downloading
          - processing_tag_data
          - generating_print_files
          - finished
  - label: Festival Foods
    handle: ff
    widgets:
      - label: Ad Tags
        handle: ad_tags
        stages:
          - downloading
          - processing_tag_data
          - generating_print_files
          - finished
      - label: Digital Coupons
        handle: digital_coupons
        stages:
          - downloading
          - processing_tag_data
          - generating_print_files
          - finished
  - label: Foodland
    handle: fl
    widgets:
      - label: Weekly
        handle: weekly
        stages:
          - downloading
          - processing_tag_data
          - generating_print_files
          - finished
  - label: Sunset Foods
    handle: sf
    widgets:
      - label: Weekly
        handle: weekly
        stages:
          - weekly_file
          - deli_file
          - servicecase_file
          - monthly_digital_deals_file
          - generating_print_files
          - finished
  - label: Family Dollar
    handle: fd
    widgets:
      - label: Monthly Kit Proofing
        handle: mk_proofing
        stages:
          - loading_orders
          - loading_psas
          - loading_details
          - building_bundled_data
          - building_hangtag_data
          - batching
          - generating_schematics
          - generating_fusionpro_inputs
          - generating_pdfs
          - generating_reports
          - building_folders
          - bundling_proofs
          - uploading
          - finished
      - label: Monthly Kit Production
        handle: mk_production
        stages:
          - loading_orders
          - loading_psas
          - loading_details
          - building_order_data
          - batching
          - inserting_batches_to_database
          - inserting_orderstats
          - generating_pdfs
          - building_folders
          - archiving
          - awaiting_completion_confirmation
          - generating_schematics
          - generating_reports
          - finished
  - label: Dollar Tree
    handle: dt
    widgets:
      - label: Import
        handle: import
        stages:
          - importing_file
          - cleaning_data
          - generating_images
          - finished
      - label: Processing Order
        handle: processing_order
        stages:
          - loading_data
          - validating_images
          - creating_files
          - finished
      - label: Strips
        handle: strips
        stages:
          - rendering_orders
          - finished
      - label: Tags
        handle: tags
        stages:
          - rendering_orders
          - finished
  - label: McCaffreys
    handle: mc
    widgets:
      - label: Weekly
        handle: weekly
        stages:
          - preflight
          - proofing
          - approval
          - production
          - finished
